temas = {
    "Filmes": [
        "O SENHOR DOS ANEIS", "HOMEM ARANHA", "BATMAN BEGINS", "A ORIGEM", "O ILUMINADO",
        "OS VINGADORES", "PANTERA NEGRA", "O REI LEAO", "A BELA E A FERA", "DIVERTIDAMENTE",
        "VIDA DE INSETO", "O BOM DINOSSAURO", "VALENTE", "WALL E", "TOY STORY",
        "UP ALTAS AVENTURAS", "OS INCRIVEIS", "MOANA", "ENCANTO", "SOUL",
        "FROZEN", "HARRY POTTER", "CORALINE", "O PEQUENO PRINCIPE", "A VIAGEM DE CHIHIRO",
        "O CASTELO ANIMADO", "MEU AMIGO TOTORO", "CARS", "CARS 2", "RELAMPAGO MCQUEEN",
        "VELOZES E FURIOSOS", "GUARDIOES DA GALAXIA", "HOMEM DE FERRO", "DOUTOR ESTRANHO", "CAPITA MARVEL",
        "THOR AMOR E TROVAO", "MATRIX", "JOHN WICK", "TOP GUN MAVERICK", "DUNA",
        "AVATAR", "TITANIC", "O TERMINADOR", "JOGOS VORAZES", "CREPUSCULO",
        "INTERESTELAR", "ELEMENTOS", "MUNDO ESTRANHO", "PLANETA DOS MACACOS", "O HOBBIT"
    ],
    "Animais": [
        "GATO MALHADO", "CACHORRO QUENTE", "TIGRE DENTE DE SABRE", "LEAO DA MONTANHA", "URSO PANDA",
        "CORUJA BURAQUEIRA", "ELEFANTE AFRICANO", "GIRAFA DO ZOO", "CAMELO DO DESERTO", "ARARA AZUL",
        "PAPAGAIO FALANTE", "CAVALO MARINHO", "GALO DE BRIGA", "JACARE DO PANTANAL", "PATO DE BOTA",
        "TUCANO COLORIDO", "TAMANDUA BANDEIRA", "COBRA CASCAVEL", "GAVIAO REAL", "SAGUI DE TUFO",
        "TATU BOLA", "LOBO GUARÁ", "CAPIVARA FELIZ", "RAPOSA VERMELHA", "CANGURU AUSTRALIANO",
        "POLVO INTELIGENTE", "GATO SIAMES", "GOLFINHO SALTADOR", "PANDA VERMELHO", "BALEIA AZUL",
        "ORNITORRINCO", "LEOPARDO DAS NEVES", "RINOCERONTE BRANCO", "TIGRE DE BENGALA", "URSO POLAR",
        "CACHORRO LABRADOR", "GATO PERSA", "CAMELO DE DUAS CORCOVAS", "COALA SONOLENTO", "TARTARUGA MARINHA",
        "PINGUIM IMPERIAL", "CAVALO DE SALTO", "GALO CANTOR", "AVESTRUZ CORREDOR", "CACHORRO PEQUINES",
        "GATO DE BOTAS", "SIRI CASCUDO", "PINTINHO AMARELINHO", "TUCANO TOCO", "GALO DA SERRA"
    ],
    "Comidas": [
        "ARROZ COM FEIJAO", "PIZZA DE MUSSARELA", "SUSHI DE SALMAO", "BOLO DE CHOCOLATE", "SORVETE DE MORANGO",
        "PASTEL DE FEIRA", "PIPOCA COM MANTEIGA", "COXINHA DE FRANGO", "PUDIM DE LEITE", "LASANHA QUENTE",
        "FRANGO A MILANESA", "MACARRAO ALHO E OLEO", "TORTA DE LIMAO", "TAPIOCA COM QUEIJO", "PAO DE QUEIJO",
        "SUCO DE LARANJA", "MILHO COZIDO", "CHURRASCO GAUCHO", "FEIJOADA COMPLETA", "CUPCAKE COLORIDO",
        "PANQUECA DOCE", "CREME DE ABACATE", "BATATA FRITA", "TOMATE RECHEADOS", "RAVIOLI AO MOLHO",
        "NHOQUE COM MOLHO", "BURGUER DE QUEIJO", "DOGAO COMPLETO", "OMELETE COM SALSINHA", "TACOS APIMENTADOS",
        "CACHORRO QUENTE", "SUFLE DE QUEIJO", "BROWNIE DE NOZES", "BRIGADEIRO DE FESTA", "BEIJINHO DE COCO",
        "CARNE DE PANELA", "MOQUECA DE PEIXE", "RISOTO DE CAMARAO", "QUIBE FRITO", "ESPAGUETE A BOLONHESA",
        "ESTROGONOFE DE CARNE", "VACA ATOLADA", "TILAPIA GRELHADA", "CAMARAO NO ALHO", "TORTA DE FRANGO",
        "SALADA RUSSA", "PAO NA CHAPA", "BOLINHO DE CHUVA", "CALDO VERDE", "ESCONDIDINHO"
    ],
    "Esportes": [
        "FUTEBOL", "BASQUETE", "VOLEI DE PRAIA", "NATACAO", "CORRIDA", "CICLISMO", "GINASTICA ARTISTICA",
        "SURFE", "SKATE", "BEISEBOL", "GOLFE", "TENIS", "HANDEBOL", "BADMINTON", "RUGBY",
        "AUTOMOBILISMO", "ESGRIMA", "HIPISMO", "ARCO E FLECHA", "MERGULHO", "XADREZ", "PATINACAO",
        "ESCALADA", "TRIATLO", "JUDO", "KARATE", "TAEKWONDO", "BOXE", "HALTEROFILISMO", "CANOAGEM",
        "REMO", "FUTSAL", "POLO AQUATICO", "ATLETISMO", "MARATONA", "LANCAMENTO DE DISCO",
        "SALTO COM VARA", "SALTO EM ALTURA", "LUCHA LIVRE", "LUTA GRECO ROMANA", "BICICLETA BMX",
        "ESCALADA INDOOR", "ESCALADA ESPORTIVA", "CORRIDA DE REVEZAMENTO", "TIRO AO ALVO", "TIRO COM ARCO",
        "CURLING", "HOQUEI NO GELO", "SNOWBOARD", "ESQUI ALPINO", "SKI CROSS"
    ],
    "Profissões": [
        "MEDICO", "ENGENHEIRO", "PROFESSOR", "ADVOGADO", "ARQUITETO", "POLICIAL", "BOMBEIRO", "ENFERMEIRO", "VETERINARIO", "DENTISTA",
        "MECANICO", "ELETRICISTA", "ENCANADOR", "CARPINTEIRO", "COZINHEIRO", "PADEIRO", "PINTOR", "CANTOR", "ATOR", "JORNALISTA",
        "PROGRAMADOR", "DESIGNER", "CINEASTA", "FOTOGRAFO", "FARMACEUTICO", "PSICOLOGO", "BIOLOGO", "QUIMICO", "FISICO", "MATEMATICO",
        "GEOLOGO", "ASTRONOMO", "SOCIOLOGO", "HISTORIADOR", "ANTROPOLOGO", "PEDAGOGO", "CORRETOR", "BANQUEIRO", "ECONOMISTA", "SECRETARIA",
        "GARCOM", "CAMINHONEIRO", "MOTORISTA", "PILOTO", "MARINHEIRO", "MERGULHADOR", "AGRICULTOR", "PECUARISTA", "ZELADOR", "SEGURANCA"
    ],
    "Objetos": [
        "CELULAR", "COMPUTADOR", "NOTEBOOK", "CARREGADOR", "TELEVISOR", "CONTROLE REMOTO", "LIVRO", "CADERNO", "CANETA", "LAPIS",
        "BORRACHA", "REGUA", "TESOURA", "MOCHILA", "CADEIRA", "MESA", "SOFA", "VENTILADOR", "GARRAFA", "COPO",
        "PRATO", "TALHERES", "GELADEIRA", "FOGAO", "MICROONDAS", "ASPIRADOR", "TECLADO", "MOUSE", "PENDRIVE", "RELOGIO",
        "OCULOS", "BONE", "CHAPEU", "ROUPA", "SAPATO", "MEIA", "GUARDA CHUVA", "ESCOVA DE DENTE", "CREME DENTAL", "SABONETE",
        "TOALHA", "CAMERA", "TRAVESSEIRO", "COBERTOR", "COLCHAO", "DESPERTADOR", "CHAVE", "CADEADO", "LANTERNA", "BATERIA"
    ],
    "Lugares": [
        "BRASIL", "EUA", "JAPAO", "CHINA", "FRANCA", "ALEMANHA", "ITALIA", "PORTUGAL", "ESPANHA", "ARGENTINA",
        "CANADA", "MEXICO", "INGLATERRA", "AUSTRALIA", "INDIA", "RUSSIA", "COREIA DO SUL", "AFRICA DO SUL", "EGITO", "GRECIA",
        "NORUEGA", "SUECIA", "DINAMARCA", "FINLANDIA", "POLONIA", "HOLANDA", "BELGICA", "IRLANDA", "ISLANDIA", "CHILE",
        "URUGUAI", "VENEZUELA", "PERU", "COLOMBIA", "PARAGUAI", "BOLIVIA", "CUBA", "JAMAICA", "PAQUISTAO", "IRA",
        "ISRAEL", "INDONESIA", "TAILANDIA", "VIETNA", "FILIPINAS", "MALASIA", "NOVA ZELANDIA", "TURQUIA", "UCRANIA", "HUNGRIA"
    ],
    "Marcas Famosas": [
        "COCA COLA", "PEPSI", "NIKE", "ADIDAS", "APPLE", "SAMSUNG", "SONY", "MICROSOFT", "GOOGLE", "AMAZON",
        "TESLA", "FORD", "CHEVROLET", "TOYOTA", "HONDA", "VOLKSWAGEN", "MCDONALDS", "BURGER KING", "KFC", "SUBWAY",
        "STARBUCKS", "NESTLE", "HEINZ", "LAYS", "PRINGLES", "DORITOS", "YOUTUBE", "FACEBOOK", "INSTAGRAM", "WHATSAPP",
        "TIKTOK", "TWITTER", "NETFLIX", "DISNEY", "PIXAR", "MARVEL", "DC COMICS", "XBOX", "PLAYSTATION", "NINTENDO",
        "UBER", "SPOTIFY", "AIRBNB", "ALIEXPRESS", "SHEIN", "ZARA", "GUCCI", "LOUIS VUITTON", "NIKE AIR", "REEBOK"
    ],
    "Jogos de Videogame": [
        "GTA SAN ANDREAS", "GTA VICE CITY", "GTA V", "FIFA", "PES", "CALL OF DUTY", "MINECRAFT", "FORTNITE", "FREE FIRE", "VALORANT",
        "CS GO", "LEAGUE OF LEGENDS", "DOTA 2", "OVERWATCH", "THE SIMS", "ASSASSINS CREED", "GOD OF WAR", "RED DEAD REDEMPTION", "THE LAST OF US", "SPIDER MAN",
        "BATMAN ARKHAM", "RESIDENT EVIL", "FIVE NIGHTS AT FREDDYS", "AMONG US", "FALLOUT", "DOOM", "HALO", "UNCHARTED", "SKYRIM", "THE WITCHER",
        "FARMING SIMULATOR", "EURO TRUCK", "FORZA HORIZON", "GRAN TURISMO", "METAL GEAR SOLID", "CASTLEVANIA", "STREET FIGHTER", "MORTAL KOMBAT", "TEKKEN", "SMASH BROS",
        "POKEMON", "ZELDA", "MARIO KART", "SUPER MARIO", "KIRBY", "DONKEY KONG", "SONIC", "CRASH BANDICOOT", "SPYRO", "TOMB RAIDER"
    ]
}
